language: python

python: 3.5

install:
  - pip install pexpect
  - python -m install_texlive -c="-acfgPDFG" -p /home/travis/texlive -v
  - export PATH=/home/travis/texlive/2019/bin/x86_64-linux:$PATH

script:
  latexmk -lualatex hello.tex
