language: python

python: 3.5

install:
  - pip install pexpect

script:
  - python -m install_texlive -c="-acfgPDFG" -t 2018 -p /home/travis/texlive -v
  - export PATH=/home/travis/texlive/2018/bin/x86_64-linux:$PATH
  - latexmk -lualatex -halt-on-error -interaction=nonstopmode hello.tex
  - latexmk -c hello.tex
  - python -m install_texlive -c="-acfgPDFG" -p /home/travis/texlive -v
  - export PATH=/home/travis/texlive/2019/bin/x86_64-linux:$PATH
  - latexmk -lualatex -halt-on-error -interaction=nonstopmode hello.tex
